CREATE TABLE parameters(
    parameter_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT,
    device_id INTEGER,
    mode TEXT DEFAULT "None",
    lower_rate_limit INTEGER,
    upper_rate_limit INTEGER,
    atrial_amplitude INTEGER,
    atrial_pulse_width INTEGER,
    atrial_sensitivity FLOAT,
    arp INTEGER,
    pvarp INTEGER,
    ventricle_amplitude INTEGER,
    ventricle_pulse_width INTEGER,
    ventricle_sensitivity FLOAT,
    vrp INTEGER,
    pvarp_ext INTEGER,
    hysteresis INTEGER,
    rate_smoothing INTEGER,
    fixed_av_delay INTEGER,
    dynamic_av_delay INTEGER,
    atr_duration INTEGER,
    atr_fall_mode INTEGER,
    atr_fall_time INTEGER,
    max_sens_rate INTEGER,
    activity_threshold INTEGER,
    reaction_time INTEGER,
    response_factor INTEGER,
    recovery_time INTEGER,
    UNIQUE(username, device_id)
);